trigger:
- main

pr:
- '*'

jobs:
- job: Build
  displayName: 'Build Job'
#  pool:
#    name: ProjektPool
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Verwende die gew端nschte Python-Version

#  - script: |
#      python -m pip install --upgrade pip
#      pip install -r requirements.txt
#    displayName: 'Installiere Python-Pakete'

  - script: |
      python -m unittest discover tests
    displayName: 'F端hre Tests durch'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)'
      artifact: 'python-app'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Build
  condition: succeeded()
  pool:
    name: Default
  steps:
  - download: current
    artifact: 'python-app'
    displayName: 'Download Build Artefakt'

  - script: |
      echo "F端hre den Bereitstellungsschritt durch, z. B. kopiere Dateien auf deinen Server."
      # F端ge hier deine eigenen Bereitstellungsschritte hinzu
    displayName: 'Bereitstellungsschritte'
