trigger:
- main

pr:
- '*'

jobs:
- job: Build
  displayName: 'Build Job'

  steps:

  - powershell: |
      echo "#############################"
      echo $(Build.SourcesDirectory)
      echo "#############################"
    displayName: 'Node.js-Paket installieren'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Verwende die gewünschte Python-Version

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)'
      artifact: 'python-app'

  - script: |
      echo "#############################"
      echo '$(Build.SourcesDirectory)'
      echo "#############################"
